### ISSUE TITLE
Publications vs. Presentations

### ISSUE THREAD

**Issue by shaomeng** [NCAR/vast#100]
Is there a criterion to put something under "Publications" vs. "Presentations" categories? I found that many items under "Presentations" would be located under "Publications" if I were to classify them.

Example: "Using Neural Networks for Two Dimensional Scientific Data Compression" under "Presentation" page.

**Comment by clyne** [comment]
There's always grey area, but I think a reasonable interpretation is that publications are peer reviewed, e.g. journal article or proceedings paper. Presentations would be talks with power point slides, or a poster. 

It's not a perfect classification, but I think it works for the obvious cases.

Note, its possible that with the above "definition" some things are not classified correctly. Feel free to make corrections!

**Comment by shaomeng** [comment]
> There's always grey area, but I think a reasonable interpretation is that publications are peer reviewed, e.g. journal article or proceedings paper. Presentations would be talks with power point slides, or a poster.
> 
> It's not a perfect classification, but I think it works for the obvious cases.
> 
> Note, its possible that with the above "definition" some things are not classified correctly. Feel free to make corrections!

I think it's how I'd classify it as well. I've submitted PR #101 to address this issue.
