### ISSUE TITLE
Partial list of interns on the "About" page

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/vast#108]
While updating the staff list, I noticed we had a couple of SIPARCS interns listed in the "Alumni" section.  However, we don't have this year's interns listed and I would guess we might be short a few in the "Alumni" section as well. 

I haven't been around long enough to know who all might be missing or I'd throw in a quick PR for this as well.

**Comment by clyne** [comment]
Thanks for taking the lead on this, @kafitzgerald. @erogluorhan and @NihanthCW should be able to provide you with the names of all of the VAST SIParCS students.

**Comment by NihanthCW** [comment]
Hi @kafitzgerald ... ViSR's staff should be up-to-date. Thanks for checking! 👍

**Comment by erogluorhan** [comment]
Hi @kafitzgerald , the list of prior year presentations [here](https://www2.cisl.ucar.edu/outreach/internships/2023projects) is a good first point to look but is not clearly stating which ones are the GeoCAT ones unless title has some refernce. I will provide you with additional resources to look

**Comment by kafitzgerald** [comment]
I think I found a list in our archive on Drive.  I'll put in a PR here quickly and we can iterate from there.

**Comment by kafitzgerald** [comment]
So [apparently](https://github.com/NCAR/vast/pull/109#issuecomment-1572828601) there's already an intern list over on the [internships page](https://vast.ucar.edu/siparcs/) that's inclusive of all prior interns, but we had a few interns on the staff alumni list as well.  

I'll drop in minor PR to clean this up and hopefully avoid future confusion.
