### ISSUE TITLE
SIParCS intern page

### ISSUE THREAD

**Issue by clyne** [NCAR/vast#30]
Should we add a page with all our interns over the last few years? It might include their picture, brief bio, project they worked on, where they are now, etc.

**Comment by clyne** [comment]
What are your thoughts on this, @jukent

**Comment by jukent** [comment]
Yes sounds great. I can reach out to Virginia to see about gathering this information. We may not be able to get all interns / all interns may not want their information public so I'll ask about that too. 

We can start with this year, and see how far back we have records.

Also this page should advertise / link to VAST SIParCS projects.

**Comment by clyne** [comment]
Getting the info from Virginia may be the easy part. Figuring out how to add a page in Hugo might be the challenge :-)

Thanks!

**Comment by jukent** [comment]
https://vast.ucar.edu/siparcs/

This is my first pass at the SIParCS intern page - I think it looks good and is workable.

It doesn't have a picture or bio suggested in this issue and is only linked to from the metrics title (I can add a navbar link). To get a picture we would need every GitHub username, which was not listed in the database given to me but I could track down if we want it.

**Comment by jukent** [comment]
I think keeping on top of where students are will be a lot of work as it will need constant manual updating, but perhaps we should link to their Github usernames or a personal website if they have it?

@NihanthCW suggested we link to their past presentations: https://www2.cisl.ucar.edu/outreach/internships/2021presentations

**Comment by clyne** [comment]
> I think keeping on top of where students are will be a lot of work as it will need constant manual updating, but perhaps we should link to their Github usernames or a personal website if they have it?
> 
> @NihanthCW suggested we link to their past presentations: https://www2.cisl.ucar.edu/outreach/internships/2021presentations

GitHub user names sounds great. Agree with @NihanthCW that it would be nice to link their presentations if they are available. No need to create a maintenance headache with "where they are now".
