### ISSUE TITLE
Header doesn't scale on mobile screens

### ISSUE THREAD

**Issue by NihanthCW** [NCAR/vast#31]
On mobile screens (portrait mode), the top banner (NCAR | VAST ) doesn't scale down sufficiently. 
fwiw: [the dart page](https://dart.ucar.edu/) scales as expected.

**Comment by kmpaul** [comment]
It does on my phone.  Can you share a screenshot?

**Comment by kmpaul** [comment]
On my iPhone 13 Pro, I see this:

![IMG_BA6452B6EBB7-1](https://user-images.githubusercontent.com/11411331/180574773-3dc923ac-ff76-42bc-a7e4-7e735ceb361e.jpeg)

**Comment by NihanthCW** [comment]
![IMG_2225](https://user-images.githubusercontent.com/42777252/180576694-e2de1008-96e2-4eed-b377-3dbc1fa13dd3.PNG)

**Comment by NihanthCW** [comment]
Yes, if you see the dart website above: the hamburger menu icon is inline with the logo. 
In our page, it is moved under our logo which I feel is not where our site-visitors would expect to find the menu.
