### ISSUE TITLE
Add something about ESDS

### ISSUE THREAD

**Issue by clyne** [NCAR/vast#36]
We should add something about our involvement with ESDS, specifically, and in general our efforts to help modernize the scientific workforce and advance their ability to conduct science.

**Comment by jukent** [comment]
Should this go onto the education page? https://vast.ucar.edu/education/

We could add the office hours link to the services page? https://vast.ucar.edu/services/

Or does this count as a project? https://vast.ucar.edu/projects/

Let me know your thoughts @clyne and I can work on this.

**Comment by clyne** [comment]
I think it could go under any of those places. Your choice :-)

**Comment by jukent** [comment]
I'll do a little of all 3 - adding a new project page potentially offers the most challenges
