### ISSUE TITLE
Add a blog entry for the Pythia hackathon

### ISSUE THREAD

**Issue by clyne** [NCAR/vast#38]
Add a news item for the summer pythia hackathon

**Comment by jukent** [comment]
Going to work on this today

**Comment by jukent** [comment]
I am having some issues with sudo for installing Hugo. I think I'm just going to draft something in a Google Doc for now so I don't get held up for this for too long. 

I was wondering, do I need Hugo? Is the only way to create a new blog post with `hugo new news/my-new-blog-post.md`? Does that command do anything other than creating a new file with the desired template (which I can borrow from elsewhere in the repo)?
