### ISSUE TITLE
Naming convention inconsistency 

### ISSUE THREAD

**Issue by NihanthCW** [NCAR/vast#83]
This is a minor issue/non-issue: I see that the news articles and the supporting folders are sometimes referred to as a "blog". Eg. in the images folder, the images corresponding to the news articles are under a folder named "blog". I suggest renaming it to news to avoid confusion. 
I don't want to break any dependencies, so I am refraining from renaming it myself.

**Comment by jukent** [comment]
I'll look at this next week!
