### ISSUE TITLE
Add SPERR article to the publications page and a news post

### ISSUE THREAD

**Issue by NihanthCW** [NCAR/vast#97]
Hi Sam, 

Could you please add your SPERR article (when url is active) to the publications page.

This could also be a good topic for a news post. You just need an image and a short paragraph describing the topic. The contributors guid in the repository home page has information on how to add a news post. Lemme know if you have any questions. 

Thanks!
Nihanth

**Comment by shaomeng** [comment]
Sure. I'll do it as soon as the complete information about this publication is available.

**Comment by NihanthCW** [comment]
@shaomeng Hope your talk went well... If you think it is ready, should we revisit adding a short news article about SPERR to the VAST gallery? I say an article- but it is just a paragraph or two

**Comment by NihanthCW** [comment]
also, could you add your IPDPS presentation to the 'presentation section' of this website. Thanks!

**Comment by shaomeng** [comment]
@NihanthCW Sure, I've submitted a presentation PR. Let's discuss what a post is going to look like; I'm not very sure ;)

**Comment by NihanthCW** [comment]
> @NihanthCW Sure, I've submitted a presentation PR. Let's discuss what a post is going to look like; I'm not very sure ;)

Sure, I am hoping this can also serve as an advert for your compression algorithm. So, maybe a paragraph outlining SPERR targeted towards an end-user along with a link to the project. I'll add this to tomorrow's meeting notes. Thanks!
